// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}], // REMOVED

  // But you can create a sidebar manually
  
  ros2ModuleSidebar: [
    {
      type: 'category',
      label: 'Module 1 - The Robotic Nervous System (ROS 2)',
      items: [
        'module1/chapter1',
        'module1/chapter2',
        'module1/chapter3',
      ],
    },
    {
      type: 'category',
      label: 'Module 2 - Digital Twin',
      items: [
        'module2/gazebo-physics',
        'module2/unity-digital-twins',
        'module2/sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        'module3/isaac-sim-photorealism',
        'module3/isaac-ros-vslam',
        'module3/nav2-path-planning',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        'module4/voice-control',
        'module4/llm-planning',
        'module4/capstone-project',
      ],
    },
  ],
};

export default sidebars;