from pydantic import BaseModel, Field
from typing import List, Optional

class AgentQuery(BaseModel):
    """
    Represents a user's input to the RAG agent service.
    """
    query: str = Field(..., description="The natural language question or prompt from the user.")
    context: Optional[str] = Field(None, description="An optional text snippet to limit the agent's response context.")

class AgentResponse(BaseModel):
    """
    Represents the AI agent's answer to a user's query.
    """
    response_text: str = Field(..., description="The natural language answer generated by the AI agent.")
    source_references: Optional[List[str]] = Field(None, description="URLs or identifiers of the documents from which information was retrieved.")
    used_context: Optional[str] = Field(None, description="The specific context (retrieved chunks or provided snippet) that the agent used to formulate the answer.")

